job:
  package-manager: npm_and_yarn
  allowed-updates:
    - update-type: all
  security-updates-only: true
  ignore-conditions:
    - dependency-name: '@sparelabs/*'
  # dependencies:
  #   - protobufjs
#   security-advisories:
#     - dependency-name: protobufjs
#       advisory-id: GHSA-h755-8qp9-cq85
#       patched-versions:
#         - ">= 6.10.0, < 6.11.4"
  source:
    provider: github
    repo: gavacq/npm-deps-vuln
    directory: /
  # updating-a-pull-request: true
